-- ============================================================
-- SNOWFLAKE FINANCIAL DATA WAREHOUSE SETUP
-- For Data Engineering & Financial Analysis Project
-- ============================================================

-- -----------------------------------------------------------
-- STEP 1: CREATE WAREHOUSE (Compute Resource)
-- -----------------------------------------------------------
-- Warehouse is the compute engine that processes queries
CREATE WAREHOUSE IF NOT EXISTS FINANCE_WH
    WITH
    WAREHOUSE_SIZE = 'SMALL'
    WAREHOUSE_TYPE = 'STANDARD'
    AUTO_SUSPEND = 300           -- Auto-suspend after 5 min idle
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

-- Use the warehouse
USE WAREHOUSE FINANCE_WH;

-- -----------------------------------------------------------
-- STEP 2: CREATE DATABASE
-- -----------------------------------------------------------
-- Database is the top-level container for all data objects
CREATE DATABASE IF NOT EXISTS FINANCIAL_DB;

-- Use the database
USE DATABASE FINANCIAL_DB;

-- -----------------------------------------------------------
-- STEP 3: CREATE SCHEMAS
-- -----------------------------------------------------------
-- Schema is a logical grouping of database objects
-- RAW: For raw ingested data
-- ANALYTICS: For cleaned and transformed data
-- REPORTING: For aggregated reporting tables

CREATE SCHEMA IF NOT EXISTS FINANCIAL_DB.RAW;
CREATE SCHEMA IF NOT EXISTS FINANCIAL_DB.ANALYTICS;
CREATE SCHEMA IF NOT EXISTS FINANCIAL_DB.REPORTING;

-- -----------------------------------------------------------
-- STEP 4: CREATE TABLES WITH REALISTIC FINANCIAL DATA
-- -----------------------------------------------------------

-- 4.1: CUSTOMERS TABLE
-- Contains customer demographic and account information
USE SCHEMA FINANCIAL_DB.RAW;

CREATE TABLE IF NOT EXISTS CUSTOMERS (
    CUSTOMER_ID         NUMBER PRIMARY KEY,
    FIRST_NAME          VARCHAR(50),
    LAST_NAME           VARCHAR(50),
    EMAIL               VARCHAR(100),
    PHONE               VARCHAR(20),
    DATE_OF_BIRTH       DATE,
    GENDER              VARCHAR(10),
    MARITAL_STATUS      VARCHAR(20),
    OCCUPATION          VARCHAR(50),
    ANNUAL_INCOME       DECIMAL(15,2),
    CREDIT_SCORE        NUMBER(3),
    ACCOUNT_OPEN_DATE   DATE,
    ACCOUNT_STATUS      VARCHAR(20),
    CITY                VARCHAR(50),
    STATE               VARCHAR(50),
    COUNTRY             VARCHAR(50),
    ZIP_CODE            VARCHAR(10),
    RISK_CATEGORY       VARCHAR(20),
    CREATED_AT          TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

-- 4.2: TRANSACTIONS TABLE
-- Contains all financial transactions (deposits, withdrawals, transfers)
CREATE TABLE IF NOT EXISTS TRANSACTIONS (
    TRANSACTION_ID      NUMBER PRIMARY KEY,
    CUSTOMER_ID         NUMBER REFERENCES CUSTOMERS(CUSTOMER_ID),
    TRANSACTION_DATE    DATE,
    TRANSACTION_TYPE    VARCHAR(30),    -- DEPOSIT, WITHDRAWAL, TRANSFER, PAYMENT, INVESTMENT
    AMOUNT              DECIMAL(15,2),
    CURRENCY            VARCHAR(3) DEFAULT 'USD',
    MERCHANT_NAME       VARCHAR(100),
    MERCHANT_CATEGORY   VARCHAR(50),    -- RETAIL, FOOD, TRAVEL, TECH, HEALTHCARE, etc.
    PAYMENT_METHOD      VARCHAR(30),    -- CREDIT_CARD, DEBIT_CARD, BANK_TRANSFER, CASH, UPI
    ACCOUNT_TYPE        VARCHAR(20),    -- SAVINGS, CHECKING, INVESTMENT, CREDIT
    BALANCE_AFTER       DECIMAL(15,2),
    DESCRIPTION         VARCHAR(255),
    IS_FRAUD            BOOLEAN DEFAULT FALSE,
    FRAUD_SCORE         DECIMAL(5,2),
    DEVICE_TYPE         VARCHAR(20),    -- MOBILE, WEB, ATM, BRANCH
    LOCATION_CITY       VARCHAR(50),
    LOCATION_COUNTRY    VARCHAR(50),
    CREATED_AT          TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

-- 4.3: LOANS TABLE
-- Contains loan applications and disbursements
CREATE TABLE IF NOT EXISTS LOANS (
    LOAN_ID             NUMBER PRIMARY KEY,
    CUSTOMER_ID         NUMBER REFERENCES CUSTOMERS(CUSTOMER_ID),
    LOAN_TYPE           VARCHAR(30),    -- PERSONAL, HOME, AUTO, EDUCATION, BUSINESS
    LOAN_AMOUNT         DECIMAL(15,2),
    INTEREST_RATE       DECIMAL(5,2),
    LOAN_TERM_MONTHS    NUMBER,
    MONTHLY_PAYMENT     DECIMAL(15,2),
    APPLICATION_DATE    DATE,
    APPROVAL_DATE       DATE,
    DISBURSEMENT_DATE   DATE,
    LOAN_STATUS         VARCHAR(20),    -- PENDING, APPROVED, REJECTED, ACTIVE, CLOSED, DEFAULTED
    OUTSTANDING_BALANCE DECIMAL(15,2),
    CREDIT_RATING       VARCHAR(10),    -- AAA, AA, A, BBB, BB, B, CCC
    COLLATERAL_VALUE    DECIMAL(15,2),
    PURPOSE             VARCHAR(100),
    CREATED_AT          TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

-- 4.4: INVESTMENTS TABLE
-- Contains investment portfolio data
CREATE TABLE IF NOT EXISTS INVESTMENTS (
    INVESTMENT_ID       NUMBER PRIMARY KEY,
    CUSTOMER_ID         NUMBER REFERENCES CUSTOMERS(CUSTOMER_ID),
    ASSET_TYPE          VARCHAR(30),    -- STOCKS, BONDS, MUTUAL_FUNDS, ETFs, CRYPTO, REAL_ESTATE
    ASSET_SYMBOL        VARCHAR(20),
    ASSET_NAME          VARCHAR(100),
    PURCHASE_DATE       DATE,
    PURCHASE_PRICE      DECIMAL(15,4),
    QUANTITY            DECIMAL(15,4),
    CURRENT_PRICE       DECIMAL(15,4),
    MARKET_VALUE        DECIMAL(15,2),
    DIVIDEND_YIELD      DECIMAL(5,2),
    SECTOR              VARCHAR(50),    -- TECH, HEALTHCARE, FINANCE, ENERGY, CONSUMER, etc.
    RISK_LEVEL          VARCHAR(10),    -- LOW, MEDIUM, HIGH
    INVESTMENT_HORIZON  VARCHAR(20),    -- SHORT_TERM, MEDIUM_TERM, LONG_TERM
    CREATED_AT          TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

-- 4.5: MARKET DATA TABLE
-- Contains daily market indices and stock prices
CREATE TABLE IF NOT EXISTS MARKET_DATA (
    MARKET_ID           NUMBER PRIMARY KEY,
    TRADE_DATE          DATE,
    SYMBOL              VARCHAR(20),
    COMPANY_NAME        VARCHAR(100),
    OPEN_PRICE          DECIMAL(15,4),
    HIGH_PRICE          DECIMAL(15,4),
    LOW_PRICE           DECIMAL(15,4),
    CLOSE_PRICE         DECIMAL(15,4),
    VOLUME              NUMBER,
    MARKET_CAP          DECIMAL(20,2),
    PE_RATIO            DECIMAL(10,2),
    DIVIDEND_YIELD      DECIMAL(5,2),
    SECTOR              VARCHAR(50),
    INDEX_NAME          VARCHAR(30),    -- S&P500, NASDAQ, DOW_JONES, RUSSELL2000
    VOLATILITY_30D      DECIMAL(10,4),
    CREATED_AT          TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

-- -----------------------------------------------------------
-- STEP 5: CREATE VIEWS FOR ANALYTICS
-- -----------------------------------------------------------
USE SCHEMA FINANCIAL_DB.ANALYTICS;

-- Customer Summary View
CREATE OR REPLACE VIEW CUSTOMER_SUMMARY AS
SELECT 
    c.CUSTOMER_ID,
    c.FIRST_NAME || ' ' || c.LAST_NAME AS FULL_NAME,
    c.ANNUAL_INCOME,
    c.CREDIT_SCORE,
    c.RISK_CATEGORY,
    COUNT(DISTINCT t.TRANSACTION_ID) AS TOTAL_TRANSACTIONS,
    SUM(CASE WHEN t.TRANSACTION_TYPE = 'DEPOSIT' THEN t.AMOUNT ELSE 0 END) AS TOTAL_DEPOSITS,
    SUM(CASE WHEN t.TRANSACTION_TYPE = 'WITHDRAWAL' THEN t.AMOUNT ELSE 0 END) AS TOTAL_WITHDRAWALS,
    SUM(CASE WHEN t.TRANSACTION_TYPE = 'PAYMENT' THEN t.AMOUNT ELSE 0 END) AS TOTAL_PAYMENTS,
    COUNT(DISTINCT l.LOAN_ID) AS TOTAL_LOANS,
    SUM(l.LOAN_AMOUNT) AS TOTAL_LOAN_AMOUNT,
    SUM(i.MARKET_VALUE) AS TOTAL_INVESTMENTS,
    DATEDIFF(YEAR, c.DATE_OF_BIRTH, CURRENT_DATE()) AS AGE
FROM FINANCIAL_DB.RAW.CUSTOMERS c
LEFT JOIN FINANCIAL_DB.RAW.TRANSACTIONS t ON c.CUSTOMER_ID = t.CUSTOMER_ID
LEFT JOIN FINANCIAL_DB.RAW.LOANS l ON c.CUSTOMER_ID = l.CUSTOMER_ID
LEFT JOIN FINANCIAL_DB.RAW.INVESTMENTS i ON c.CUSTOMER_ID = i.CUSTOMER_ID
GROUP BY c.CUSTOMER_ID, c.FIRST_NAME, c.LAST_NAME, c.ANNUAL_INCOME, 
         c.CREDIT_SCORE, c.RISK_CATEGORY, c.DATE_OF_BIRTH;

-- Monthly Transaction Trends
CREATE OR REPLACE VIEW MONTHLY_TRANSACTION_TRENDS AS
SELECT 
    DATE_TRUNC('MONTH', TRANSACTION_DATE) AS MONTH,
    TRANSACTION_TYPE,
    MERCHANT_CATEGORY,
    COUNT(*) AS TRANSACTION_COUNT,
    SUM(AMOUNT) AS TOTAL_AMOUNT,
    AVG(AMOUNT) AS AVG_AMOUNT,
    STDDEV(AMOUNT) AS STD_AMOUNT
FROM FINANCIAL_DB.RAW.TRANSACTIONS
GROUP BY DATE_TRUNC('MONTH', TRANSACTION_DATE), TRANSACTION_TYPE, MERCHANT_CATEGORY;

-- -----------------------------------------------------------
-- STEP 6: CREATE REPORTING TABLES
-- -----------------------------------------------------------
USE SCHEMA FINANCIAL_DB.REPORTING;

-- Risk Analysis Report
CREATE TABLE IF NOT EXISTS RISK_ANALYSIS (
    REPORT_DATE         DATE,
    RISK_CATEGORY       VARCHAR(20),
    CUSTOMER_COUNT      NUMBER,
    AVG_CREDIT_SCORE    DECIMAL(6,2),
    TOTAL_EXPOSURE      DECIMAL(20,2),
    DEFAULT_RATE        DECIMAL(5,2),
    FRAUD_RATE          DECIMAL(5,2),
    AVG_LOAN_AMOUNT     DECIMAL(15,2),
    CREATED_AT          TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

-- Investment Performance Report
CREATE TABLE IF NOT EXISTS INVESTMENT_PERFORMANCE (
    REPORT_DATE         DATE,
    ASSET_TYPE          VARCHAR(30),
    SECTOR              VARCHAR(50),
    TOTAL_INVESTED      DECIMAL(20,2),
    CURRENT_VALUE       DECIMAL(20,2),
    RETURN_PCT          DECIMAL(10,2),
    AVG_DIVIDEND_YIELD  DECIMAL(5,2),
    CUSTOMER_COUNT      NUMBER,
    CREATED_AT          TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

-- -----------------------------------------------------------
-- STEP 7: SETUP PERMISSIONS (Optional)
-- -----------------------------------------------------------
-- Grant usage on database and schema
-- GRANT USAGE ON DATABASE FINANCIAL_DB TO ROLE YOUR_ROLE;
-- GRANT USAGE ON SCHEMA FINANCIAL_DB.RAW TO ROLE YOUR_ROLE;
-- GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA FINANCIAL_DB.RAW TO ROLE YOUR_ROLE;

-- -----------------------------------------------------------
-- STEP 8: RESUME WAREHOUSE
-- -----------------------------------------------------------
ALTER WAREHOUSE FINANCE_WH RESUME;

SELECT 'Snowflake Financial Data Warehouse Setup Complete!' AS STATUS;
